server:
  port: 8081
  servlet:
    context-path: /myapp
    session:
      cookie:
        path: /
        max-age: 999999999  
      timeout: 999999999  
  tomcat:
    accept-count: 5
    max-threads: 1000  
spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 10MB
  mvc:
    view:
      prefix: /page/
      suffix: .html
  jmx:
    enabled: false
  devtools:
    restart:
      enabled: false
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure.include: "*"
      base-path: /Actuator
  server:
      port: 8085
      address: 127.0.0.1
logging:
  file: /home/yizhi/logging/myapp.log
  level:
    org.springframework.boot.autoconfigure: ERROR 
    org.mongodb.driver: ERROR
    com.zihai.websocket.HomeEventHandler: DEBUG
    com.zihai.websocket.EventChatHandler: DEBUG
    org.springframework.boot.web.servlet.* : INFO
    root: INFO